#' Execute neoBAM operations

# Libraries
library(parallel)
library(doParallel)

#' Execute neoBAM
#'
#' @param neobam_data_and_priors named list of SWOT data, priors, and parameters
#' @param sourcefile string path to .stan file
#'
#' @return list of posteriors (r, logn, logWb, logDb)
execute_neobam = function(neobam_data_and_priors, sourcefile) {
  return(list(run_neobam(neobam_data_and_priors, sourcefile)))
}

#' Retrieve discharge time series
#'
#' @param index integer index to select posteriors
#' @param width SWOT width matrix
#' @param slope2 SWOT slope2 matrix
#' @param posteriors named list of posteriors generated by neoBAM
#'
#' @return list of discharge time series
retrieve_discharge = function(index, width, slope2, posteriors) {
  return(list(remake_discharge(data$swot_data$width, data$swot_data$slope2, posteriors[[index]])))
}

#' Run neoBAM on input data.
#'
#' @param data named list of observation data (SWOT and Q priors)
#' @param stanfile string path to .stan file
#'
#' @return posteriors
#' @export
process_data = function(data, stan_file) {

  # Window sample and parameters
  windowed = window_mode(data$swot_data$width, data$swot_data$slope2,
                         data$swot_data$time, GLOBAL_PARAMS$perc_lower,
                         GLOBAL_PARAMS$perc_upper, GLOBAL_PARAMS$nt_window,
                         GLOBAL_PARAMS$nx_sample, data$sos_data$window_params)

  # Generate priors
  neobam_prep_data = NA
  data_and_priors = generate_neobam_priors_and_data(windowed,
                                                    data$sos_data$Q_priors,
                                                    neobam_prep_data,
                                                    GLOBAL_PARAMS,
                                                    windowed$priors)

  # Execute neoBAM three times
  #cl <- makeCluster(3)
  #registerDoParallel(cl)
  #print('here is the stan file')
  #print(stan_file)
  #posteriors = foreach(index=1:3, .combine='c', .export=c("execute_neobam", "run_neobam")) %dopar%
  #  execute_neobam(neobam_data_and_priors=data_and_priors, sourcefile=stan_file)
#
  # Generate discharge time series
 # discharge = foreach(index=1:3, .combine='c', .export=c("retrieve_discharge", "remake_discharge")) %dopar%
  #  retrieve_discharge(index, width=data$swot_data$width, slope2=data$swot_data$slope2, posteriors=posteriors)
  #stopCluster(cl)

  #return(list(discharge=discharge, posteriors=posteriors))

  for (i in 1:3){
      posteriors=execute_neobam(neobam_data_and_priors=data_and_priors, sourcefile=stan_file)
      discharge=retrieve_discharge(width=data$swot_data$width, slope2=data$swot_data$slope2, posteriors=posteriors)
    }


  
}
